In [1]:
import numpy as np

In [2]:
arr=np.random.randint(0,10,(4,4))

In [3]:
arr

array([[1, 0, 9, 1],
       [1, 2, 1, 1],
       [4, 3, 0, 8],
       [2, 4, 4, 9]], dtype=int32)

In [5]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
arr

array([[1, 0, 9, 1],
       [1, 2, 1, 1],
       [4, 3, 0, 8],
       [2, 4, 4, 9]], dtype=int32)

In [10]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [16]:
np.arange(0,15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [17]:
np.linspace(0,100,8)

array([  0.        ,  14.28571429,  28.57142857,  42.85714286,
        57.14285714,  71.42857143,  85.71428571, 100.        ])

In [18]:
arr

array([[1, 0, 9, 1],
       [1, 2, 1, 1],
       [4, 3, 0, 8],
       [2, 4, 4, 9]], dtype=int32)

Banking Industry Analysis

In [158]:
import pandas as pd
import numpy as np

data = {
    "Customer_ID": [101,102,103,104,105,106,107,108,109,110],
    "Account_Balance": [1200,5400,2300,7800,1500,6200,9100,3000,4500,6700],
    "Credit_Score": [650,720,600,800,580,690,820,610,700,750],
    "Transaction_Count": [12,25,10,40,8,30,50,15,22,35],
    "Years_Active": [2,5,3,10,1,7,12,4,6,8]
}

df = pd.DataFrame(data)

print(df)

   Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
0          101             1200           650                 12             2
1          102             5400           720                 25             5
2          103             2300           600                 10             3
3          104             7800           800                 40            10
4          105             1500           580                  8             1
5          106             6200           690                 30             7
6          107             9100           820                 50            12
7          108             3000           610                 15             4
8          109             4500           700                 22             6
9          110             6700           750                 35             8

In [28]:
df.shape

(10, 5)

In [29]:
df.size

50

In [30]:
df.dtypes

Customer_ID          int64
Account_Balance      int64
Credit_Score         int64
Transaction_Count    int64
Years_Active         int64
dtype: object

In [31]:
df.ndim

2

In [50]:
df=df.to_numpy()
print(df.nbytes)

400

In [45]:
df.iloc[0:4,0:4]

   Customer_ID  Account_Balance  Credit_Score  Transaction_Count
0          101             1200           650                 12
1          102             5400           720                 25
2          103             2300           600                 10
3          104             7800           800                 40

In [52]:
df[0]

array([ 101, 1200,  650,   12,    2])

In [53]:
df[-1]

array([ 110, 6700,  750,   35,    8])

In [61]:
df["Account_Balance"]

0    1200
1    5400
2    2300
3    7800
4    1500
5    6200
6    9100
7    3000
8    4500
9    6700
Name: Account_Balance, dtype: int64

In [62]:
df

   Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
0          101             1200           650                 12             2
1          102             5400           720                 25             5
2          103             2300           600                 10             3
3          104             7800           800                 40            10
4          105             1500           580                  8             1
5          106             6200           690                 30             7
6          107             9100           820                 50            12
7          108             3000           610                 15             4
8          109             4500           700                 22             6
9          110             6700           750                 35             8

In [64]:
df[3:9]

   Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
3          104             7800           800                 40            10
4          105             1500           580                  8             1
5          106             6200           690                 30             7
6          107             9100           820                 50            12
7          108             3000           610                 15             4
8          109             4500           700                 22             6

In [66]:
df['Account_Balance'].sum()

np.int64(47700)

In [67]:
df['Account_Balance'].mean()

np.float64(4770.0)

In [68]:
df['Account_Balance'].std()

np.float64(2725.211510649729)

In [69]:
df['Account_Balance'].var()

np.float64(7426777.777777778)

In [70]:
df['Account_Balance'].median()

np.float64(4950.0)

In [71]:
df['Account_Balance'].min()

np.int64(1200)

In [72]:
df['Account_Balance'].max()

np.int64(9100)

In [73]:
df['Credit_Score'].min()

np.int64(580)

In [74]:
df['Account_Balance'].max()

np.int64(9100)

In [79]:
df['Account_Balance'].quantile(0.25)

np.float64(2475.0)

In [80]:
df['Account_Balance'].quantile(0.50)

np.float64(4950.0)

In [86]:
print(df['Account_Balance'].corr(df['Credit_Score']))

0.9324862142065987

In [87]:
df['Account_Balance'].cov(df['Credit_Score'])

np.float64(210511.1111111111)

In [97]:
df.values.reshape(5,10)

array([[ 101, 1200,  650,   12,    2,  102, 5400,  720,   25,    5],
       [ 103, 2300,  600,   10,    3,  104, 7800,  800,   40,   10],
       [ 105, 1500,  580,    8,    1,  106, 6200,  690,   30,    7],
       [ 107, 9100,  820,   50,   12,  108, 3000,  610,   15,    4],
       [ 109, 4500,  700,   22,    6,  110, 6700,  750,   35,    8]])

In [106]:
df=df.to_numpy()

In [111]:
df

   Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
0          101             1200           650                 12             2
1          102             5400           720                 25             5
2          103             2300           600                 10             3
3          104             7800           800                 40            10
4          105             1500           580                  8             1
5          106             6200           690                 30             7
6          107             9100           820                 50            12
7          108             3000           610                 15             4
8          109             4500           700                 22             6
9          110             6700           750                 35             8

In [112]:
np.ravel(df)

array([ 101, 1200,  650,   12,    2,  102, 5400,  720,   25,    5,  103,
       2300,  600,   10,    3,  104, 7800,  800,   40,   10,  105, 1500,
        580,    8,    1,  106, 6200,  690,   30,    7,  107, 9100,  820,
         50,   12,  108, 3000,  610,   15,    4,  109, 4500,  700,   22,
          6,  110, 6700,  750,   35,    8])

In [113]:
np.transpose(df)

                      0     1     2     3     4     5     6     7     8     9
Customer_ID         101   102   103   104   105   106   107   108   109   110
Account_Balance    1200  5400  2300  7800  1500  6200  9100  3000  4500  6700
Credit_Score        650   720   600   800   580   690   820   610   700   750
Transaction_Count    12    25    10    40     8    30    50    15    22    35
Years_Active          2     5     3    10     1     7    12     4     6     8

In [115]:
np.vsplit(df,2)

[array([[ 101, 1200,  650,   12,    2],
        [ 102, 5400,  720,   25,    5],
        [ 103, 2300,  600,   10,    3],
        [ 104, 7800,  800,   40,   10],
        [ 105, 1500,  580,    8,    1]]),
 array([[ 106, 6200,  690,   30,    7],
        [ 107, 9100,  820,   50,   12],
        [ 108, 3000,  610,   15,    4],
        [ 109, 4500,  700,   22,    6],
        [ 110, 6700,  750,   35,    8]])]

In [120]:
np.hsplit(df,5)

[array([[101],
        [102],
        [103],
        [104],
        [105],
        [106],
        [107],
        [108],
        [109],
        [110]]),
 array([[1200],
        [5400],
        [2300],
        [7800],
        [1500],
        [6200],
        [9100],
        [3000],
        [4500],
        [6700]]),
 array([[650],
        [720],
        [600],
        [800],
        [580],
        [690],
        [820],
        [610],
        [700],
        [750]]),
 array([[12],
        [25],
        [10],
        [40],
        [ 8],
        [30],
        [50],
        [15],
        [22],
        [35]]),
 array([[ 2],
        [ 5],
        [ 3],
        [10],
        [ 1],
        [ 7],
        [12],
        [ 4],
        [ 6],
        [ 8]])]

In [126]:
df[df['Account_Balance'] > 10000][['Customer_ID', 'Account_Balance']]

Empty DataFrame
Columns: [Customer_ID, Account_Balance]
Index: []

In [128]:
df[df['Credit_Score']>800]

   Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
6          107             9100           820                 50            12

In [134]:
df[(df['Transaction_Count'] > 50) & (df['Credit_Score'] < 750)]

Empty DataFrame
Columns: [Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active]
Index: []

In [138]:
df[(df['Account_Balance'] > 10000) & (df['Account_Balance'] < 100000)].shape[0]

0

In [145]:
df['Credit_Score'].idxmax()

6

In [147]:
df.sort_values(by='Account_Balance',ascending=True)

   Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
0          101             1200           650                 12             2
4          105             1500           580                  8             1
2          103             2300           600                 10             3
7          108             3000           610                 15             4
8          109             4500           700                 22             6
1          102             5400           720                 25             5
5          106             6200           690                 30             7
9          110             6700           750                 35             8
3          104             7800           800                 40            10
6          107             9100           820                 50            12

In [148]:
df.sort_values(by='Credit_Score',ascending=True)

   Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
4          105             1500           580                  8             1
2          103             2300           600                 10             3
7          108             3000           610                 15             4
0          101             1200           650                 12             2
5          106             6200           690                 30             7
8          109             4500           700                 22             6
1          102             5400           720                 25             5
9          110             6700           750                 35             8
3          104             7800           800                 40            10
6          107             9100           820                 50            12

In [155]:
indices = df['Years_Active'].argsort()

In [156]:
indices

0    4
1    0
2    2
3    7
4    1
5    8
6    5
7    9
8    3
9    6
Name: Years_Active, dtype: int64

In [157]:
df

   Customer_ID  Account_Balance  Credit_Score  Transaction_Count  Years_Active
0          101             1200           650                 12             2
1          102             5400           720                 25             5
2          103             2300           600                 10             3
3          104             7800           800                 40            10
4          105             1500           580                  8             1
5          106             6200           690                 30             7
6          107             9100           820                 50            12
7          108             3000           610                 15             4
8          109             4500           700                 22             6
9          110             6700           750                 35             8

In [168]:
sorted_acc=df[['Customer_ID','Account_Balance']].sort_values(by='Account_Balance',ascending=False)

In [171]:
sorted_acc.iloc[1]

Customer_ID         104
Account_Balance    7800
Name: 3, dtype: int64

In [172]:
arr=np.random.randint(1,10,(4,4))

In [173]:
arr

array([[4, 1, 9, 3],
       [8, 4, 3, 5],
       [3, 4, 3, 5],
       [2, 6, 1, 7]], dtype=int32)